version: "3"
volumes:
  postgresql_agnostos_data:
services:
  postgresql_agnostos:
    image: "docker.io/postgres:alpine"
    hostname: "postgres_agnostos"
    container_name: "postgres_planet_ota"
    restart: on-failure
    volumes:
      - "postgresql_agnostos_data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=${DB_USER:-agnostos_user}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD:-password123}"
      - "POSTGRES_DB=${DB_NAME:-agnostos_db}"
  agnostos:
    build: "."
    image: "ghcr.io/shymega/agnostos:latest"
    hostname: "agnostos"
    container_name: "agnostos"
    restart: on-failure
    environment:
      TZ: "Europe/London"
    depends_on:
      - postgresql_agnostos
    ports:
      - "8080:8080"
