version: "3"
volumes:
  postgresql_ota_data:
services:
  postgresql_ota:
    image: "docker.io/postgres:alpine"
    hostname: "postgres_ota"
    container_name: "postgres_ota"
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_ota_data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=planet_ota_service"
      - "POSTGRES_PASSWORD=password123"
      - "POSTGRES_DB=planet_ota_service"
  ironauth:
    image: "docker.io/iron/auth"
    container_name: "ironauth"
    hostname: "ironauth"
    ports:
      - "8090:8090"
  ironmq:
    image: "docker.io/iron/mq"
    container_name: "ironmq"
    hostname: "ironmq"
    environment:
      - "AUTH_HOST=http://ironauth:8090"
    ports:
      - "8070:8080"
  planet_ota_service:
    build: "."
    hostname: "planet_ota_service"
    container_name: "planet_ota_service"
    ports:
      - "8080:8080"

