version: "3"
volumes:
  postgresql_ota_data:
services:
  postgresql_ota:
    image: "docker.io/postgres:alpine"
    hostname: "postgres_ota"
    container_name: "postgres_ota"
    volumes:
      - "postgresql_ota_data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=planet_ota_service"
      - "POSTGRES_PASSWORD=password123"
      - "POSTGRES_DB=planet_ota_service"
  planet_ota_service:
    build: "."
    hostname: "planet_ota_service"
    container_name: "planet_ota_service"
    ports:
      - "8080:8080"

