name: CI container image builder

on:
  workflow_run:
    workflows: ["CodeQL workflow"]
    types: [completed]
    branches: [main]

jobs:
  build-agnostos-container-image:
    name: Build and push container image to GHCR
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build images
        id: build
        uses: redhat-actions/buildah-build@v2.12
        with:
          image: ${{ github.repository }}
          tags: ${{ contains(github.ref_name, 'main') && 'latest' || github.ref_name }}
          containerfiles: Dockerfile

      - name: Push container to GHCR.io
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
