name: CI container image builder

on:
  workflow_run:
    workflows: ["CI workflow"]
    types: [completed]
    branches: [main]

jobs:
  build-ota-service-container-image:
    name: Build and push container image to GHCR
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Build images
        id: build
        uses: redhat-actions/buildah-build@v2.11
        with:
          image: ${{ github.repository }}
          tags: sha-${{ github.sha }}
          containerfiles: Dockerfile

      - name: Push container to GHCR.io
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
